### ISSUE TITLE
Pre-compiled dll available on repository

### ISSUE THREAD

**Issue by joscandreu** [ailton07/PinVMShield#1]
Hello,

I am currently trying to use PinVMShield but I am having trouble compiling myself the dll. Could you upload to the repository an already compiled dll of your code version?
I have tried to use the dll included, but I think is the original one that appeared on the original project from https://bitbucket.org/rjrodriguez/pinvmshield, right?

I am getting an error when using pin 2.14 with the old precompiled dll.

Thanks.

Regards,

**Comment by ailton07** [comment]
Hello, José Carlos,

Thank you for your interest.
You are right, the file "PinVMShield-1.0.dll" is the original DLL.
Sure, I have already uploaded it. I used Pin 2.14. (src/Debug/PinVMShield.dll)

Thanks.

Best regards.

**Comment by joscandreu** [comment]
Amazing!
Thanks for your cooperation and being so fast.
